<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bom extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bom_model');
        $this->load->model('Bahan_model');
        $this->load->model('Detail_bom_model');

        $this->load->model('Produk_model');
        $this->load->model('Custom_model');
    }

    function add_detail($id)
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('id_bahan','Id Bahan','required|integer');
        $this->form_validation->set_rules('jumlah','Jumlah','required');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'id_bahan' => $this->input->post('id_bahan'),
                'id_bom' => $id,
                'jumlah' => $this->input->post('jumlah'),
            );
            
            $detail_bom_id = $this->Detail_bom_model->add_detail_bom($params);

            $bom = $this->Bom_model->get_bom($id);

            $bahan = $this->Bahan_model->get_all_bahan();
            $total=$bom['total'];
            foreach($bahan as $b){
                if($b['id']==$this->input->post('id_bahan')){
                    
                    $total = $total + $this->input->post('jumlah')*$b['harga'];
                }
            }

            $this->editbom($id,$total);
            redirect('bom/index');
        }
        else
        {
            $this->load->model('Bahan_model');
            $data['all_bahan'] = $this->Bahan_model->get_all_bahan();
            $data['_view'] = 'detail_bom/add';
            $data['id'] = $id;
            $this->load->view('layouts/main',$data);
        }
    }   

    function editbom($id,$total)
    {   
        
                $params = array(
                    'total' => $total
                );

                $this->Bom_model->update_bom($id,$params);            
               
      
    } 

    /*
     * Listing of bom
     */
    function index()
    {
        $data['bom'] = $this->Bom_model->get_all_bom();
        $data['detail_bom'] = $this->Detail_bom_model->get_all_detail_bom();
        $data['bahan'] = $this->Bahan_model->get_all_bahan();
        
        $data['_view'] = 'bom/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bom
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required|max_length[25]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama')
            );
            
            $bom_id = $this->Bom_model->add_bom($params);
            redirect('bom/index');
        }
        else
        {            
            $data['_view'] = 'bom/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bom
     */
    function edit($id)
    {   
        // check if the bom exists before trying to edit it
        $data['bom'] = $this->Bom_model->get_bom($id);
        
        if(isset($data['bom']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required|max_length[25]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama')
                );

                $this->Bom_model->update_bom($id,$params);            
                redirect('bom/index');
            }
            else
            {
                $data['_view'] = 'bom/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bom you are trying to edit does not exist.');
    } 

    /*
     * Deleting bom
     */
    function remove($id)
    {
        $bom = $this->Bom_model->get_bom($id);

        $detail = $this->Produk_model->get_all_produk();
        $detail2 = $this->Custom_model->get_all_custom();
        $ada = false;

        foreach($detail as $d){
            if($d['id_bom']==$id){
                $ada=true;
            }
        }

        foreach($detail2 as $d){
            if($d['id_bom']==$id){
                $ada=true;
            }
        }

        // check if the bom exists before trying to delete it
        if(isset($bom['id'])&&$ada==false)
        {
            $this->Bom_model->delete_bom($id);
            redirect('bom/index');
        }
        else
            echo "<script>alert('Data digunakan oleh Tabel lain !');</script>";
            $data['bom'] = $this->Bom_model->get_all_bom();
            $data['detail_bom'] = $this->Detail_bom_model->get_all_detail_bom();
            $data['bahan'] = $this->Bahan_model->get_all_bahan();
        
            $data['_view'] = 'bom/index';
            $this->load->view('layouts/main',$data);
    }
    
}
