<?php 
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Custom extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Custom_model');

        $this->load->model('Katalog_model');

        $this->load->model('Bom_model');
    } 

    /*
     * Listing of custom
     */
    function index()
    {
        $data['custom'] = $this->Custom_model->getAll();

        $data['katalog'] = $this->Katalog_model->get_all_katalog();

        
        $data['bom'] = $this->Bom_model->get_all_bom(); 
        $data['_view'] = 'custom/index';
        $this->load->view('layouts/main',$data);
    }


    function add()
    {   
        $custom = $this->Custom_model;
        $validation = $this->form_validation;
        $validation->set_rules($custom->rules());
        
        if ($validation->run()) {
            $custom->save();
            $this->session->set_flashdata('success', 'Berhasil disimpan');

            redirect(site_url('custom/index')); 
        }

        $this->load->model('Katalog_model');
        $data['all_katalog'] = $this->Katalog_model->get_all_katalog();

        $this->load->model('Bom_model');
        $data['all_bom'] = $this->Bom_model->get_all_bom();
            
        $data['_view'] = 'custom/add';
        $this->load->view('layouts/main',$data);;
    }

    function edit($id=null)
    {   
        if (!isset($id)) redirect('custom/index');
       
        $custom = $this->Custom_model;
        $validation = $this->form_validation;
        $validation->set_rules($custom->rules());

        if ($validation->run()) {
            $custom->update($id);
            $this->session->set_flashdata('success', 'Berhasil disimpan');
            redirect(site_url('custom/index'));
        }

        $data["custom"] = $custom->getById($id);
        if (!$data["custom"]) show_404();

        $this->load->model('Katalog_model');
        $data['all_katalog'] = $this->Katalog_model->get_all_katalog();

        $this->load->model('Bom_model');
        $data['all_bom'] = $this->Bom_model->get_all_bom();
        
         $data['_view'] = 'custom/edit';
        $this->load->view('layouts/main',$data);
    }

   function remove($id=null)
    {

        if (!isset($id)) show_404();
        
        if ($this->Custom_model->delete($id)) {
            redirect(site_url('custom/index'));
        }
    }
    
}
