<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Produk_model');
        
    }

    function index()
    {	
    	$query = $this->db->query('SELECT * FROM produk');

		$data['produk'] = $query->num_rows();

		$query = $this->db->query('SELECT * FROM customer');

		$data['customer'] = $query->num_rows();

		$query = $this->db->query('SELECT * FROM penjualan where status=1');

		$data['masuk'] = $query->num_rows();

		$query = $this->db->query('SELECT * FROM penjualan where status>=4 and status <=5 ');

		$data['kerja'] = $query->num_rows();

		$query = $this->db->query('SELECT * FROM penjualan where status=7');

		$data['done'] = $query->num_rows();

		$penjualan = $query->result();

        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data); 
    }
}
