<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Karyawan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Karyawan_model');
    } 

    /*
     * Listing of karyawan
     */
    function index()
    {
        $data['karyawan'] = $this->Karyawan_model->get_all_karyawan();
        
        $data['_view'] = 'karyawan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new karyawan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|max_length[32]');
		$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
        $this->form_validation->set_rules('nip','NIP','required|max_length[9]');
		$this->form_validation->set_rules('email','Email','required|max_length[100]|valid_email');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => md5($this->input->post('password')),
                'nip' => $this->input->post('nip'),
				'nama' => $this->input->post('nama'),
				'email' => $this->input->post('email'),
            );
            
            $karyawan_id = $this->Karyawan_model->add_karyawan($params);
            redirect('karyawan/index');
        }
        else
        {            
            $data['_view'] = 'karyawan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a karyawan
     */
    function edit($id)
    {   
        // check if the karyawan exists before trying to edit it
        $data['karyawan'] = $this->Karyawan_model->get_karyawan($id);
        
        if(isset($data['karyawan']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','required|max_length[32]');
			$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
            $this->form_validation->set_rules('nip','NIP','required|max_length[9]');
			$this->form_validation->set_rules('email','Email','required|max_length[100]|valid_email');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
                    'nip' => $this->input->post('nip'),
					'nama' => $this->input->post('nama'),
					'email' => $this->input->post('email'),
                );

                $this->Karyawan_model->update_karyawan($id,$params);            
                redirect('karyawan/index');
            }
            else
            {
                $data['_view'] = 'karyawan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The karyawan you are trying to edit does not exist.');
    } 

    /*
     * Deleting karyawan
     */
    function remove($id)
    {
        $karyawan = $this->Karyawan_model->get_karyawan($id);

        // check if the karyawan exists before trying to delete it
        if(isset($karyawan['id']))
        {
            $this->Karyawan_model->delete_karyawan($id);
            redirect('karyawan/index');
        }
        else
            show_error('The karyawan you are trying to delete does not exist.');
    }
    
}
