<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Katalog extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Katalog_model');
        $this->load->model('Produk_model');
        $this->load->model('Custom_model');
    } 

    /*
     * Listing of katalog
     */
    function index()
    {
        $data['katalog'] = $this->Katalog_model->get_all_katalog();
        
        $data['_view'] = 'katalog/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new katalog
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required|max_length[25]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
            );
            
            $katalog_id = $this->Katalog_model->add_katalog($params);
            redirect('katalog/index');
        }
        else
        {            
            $data['_view'] = 'katalog/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a katalog
     */
    function edit($id)
    {   
        // check if the katalog exists before trying to edit it
        $data['katalog'] = $this->Katalog_model->get_katalog($id);
        
        if(isset($data['katalog']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required|max_length[25]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
                );

                $this->Katalog_model->update_katalog($id,$params);            
                redirect('katalog/index');
            }
            else
            {
                $data['_view'] = 'katalog/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The katalog you are trying to edit does not exist.');
    } 

    /*
     * Deleting katalog
     */
    function remove($id)
    {
        $katalog = $this->Katalog_model->get_katalog($id);
        $detail = $this->Produk_model->get_all_produk();
        $detail2 = $this->Custom_model->get_all_custom();
        $ada = false;

        foreach($detail as $d){
            if($d['id_katalog']==$id){
                $ada=true;
            }
        }

        foreach($detail2 as $d){
            if($d['id_katalog']==$id){
                $ada=true;
            }
        }

        // check if the katalog exists before trying to delete it
        if(isset($katalog['id'])&&$ada!=true)
        {
            $this->Katalog_model->delete_katalog($id);
            redirect('katalog/index');
        }
        else
            echo "<script>alert('Data digunakan oleh Tabel lain !');</script>";
            $data['katalog'] = $this->Katalog_model->get_all_katalog();
        
            $data['_view'] = 'katalog/index';
            $this->load->view('layouts/main',$data);
    }
    
}
