<?php  
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Produk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Produk_model');
        $this->load->model('Katalog_model');
        
        $this->load->model('Bom_model');
    } 

    /*
     * Listing of produk
     */
    function index()
    {
        $data['produk'] = $this->Produk_model->getAll();
        $data['katalog'] = $this->Katalog_model->get_all_katalog();
        
        $data['bom'] = $this->Bom_model->get_all_bom();
        $data['_view'] = 'produk/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new produk
     */
    function add()
    {   
        $produk = $this->Produk_model;
        $validation = $this->form_validation;
        $validation->set_rules($produk->rules());
		
		if ($validation->run()) {
            $produk->save();
            $this->session->set_flashdata('success', 'Berhasil disimpan');

            redirect(site_url('produk/index')); 
        }

        $this->load->model('Katalog_model');
        $data['all_katalog'] = $this->Katalog_model->get_all_katalog();

        $this->load->model('Bom_model');
        $data['all_bom'] = $this->Bom_model->get_all_bom();
            
        $data['_view'] = 'produk/add';
        $this->load->view('layouts/main',$data);;
    }  

    /*
     * Editing a produk
     */
    function edit($id=null)
    {   
        if (!isset($id)) redirect('produk/index');
       
        $produk = $this->Produk_model;
        $validation = $this->form_validation;
        $validation->set_rules($produk->rules());

        if ($validation->run()) {
            $produk->update($id);
            $this->session->set_flashdata('success', 'Berhasil disimpan');
            redirect(site_url('produk/index'));
        }

        $data["produk"] = $produk->getById($id);
        if (!$data["produk"]) show_404();

        $this->load->model('Katalog_model');
        $data['all_katalog'] = $this->Katalog_model->get_all_katalog();

        $this->load->model('Bom_model');
        $data['all_bom'] = $this->Bom_model->get_all_bom();
        
         $data['_view'] = 'produk/edit';
        $this->load->view('layouts/main',$data);
    } 

    /*
     * Deleting produk
     */
    function remove($id=null)
    {

        if (!isset($id)) show_404();
        
        if ($this->Produk_model->delete($id)) {
            redirect(site_url('produk/index'));
        }
    }
    
}
