<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sablon_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sablon_detail_model');
    } 

    /*
     * Listing of sablon_detail
     */
    function index()
    {
        $data['sablon_detail'] = $this->Sablon_detail_model->get_all_sablon_detail();
        
        $data['_view'] = 'sablon_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sablon_detail
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_keranjang','Id Keranjang','required|integer');
		$this->form_validation->set_rules('id_bom','Id Bom','required|integer');
		$this->form_validation->set_rules('type','Type','required|integer');
		$this->form_validation->set_rules('gambar','Gambar','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_keranjang' => $this->input->post('id_keranjang'),
				'id_bom' => $this->input->post('id_bom'),
				'type' => $this->input->post('type'),
				'gambar' => $this->input->post('gambar'),
            );
            
            $sablon_detail_id = $this->Sablon_detail_model->add_sablon_detail($params);
            redirect('sablon_detail/index');
        }
        else
        {            
            $data['_view'] = 'sablon_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sablon_detail
     */
    function edit($id)
    {   
        // check if the sablon_detail exists before trying to edit it
        $data['sablon_detail'] = $this->Sablon_detail_model->get_sablon_detail($id);
        
        if(isset($data['sablon_detail']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_keranjang','Id Keranjang','required|integer');
			$this->form_validation->set_rules('id_bom','Id Bom','required|integer');
			$this->form_validation->set_rules('type','Type','required|integer');
			$this->form_validation->set_rules('gambar','Gambar','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_keranjang' => $this->input->post('id_keranjang'),
					'id_bom' => $this->input->post('id_bom'),
					'type' => $this->input->post('type'),
					'gambar' => $this->input->post('gambar'),
                );

                $this->Sablon_detail_model->update_sablon_detail($id,$params);            
                redirect('sablon_detail/index');
            }
            else
            {
                $data['_view'] = 'sablon_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sablon_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting sablon_detail
     */
    function remove($id)
    {
        $sablon_detail = $this->Sablon_detail_model->get_sablon_detail($id);

        // check if the sablon_detail exists before trying to delete it
        if(isset($sablon_detail['id']))
        {
            $this->Sablon_detail_model->delete_sablon_detail($id);
            redirect('sablon_detail/index');
        }
        else
            show_error('The sablon_detail you are trying to delete does not exist.');
    }
    
}
