<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bahan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bahan by id
     */
    function get_bahan($id)
    {
        return $this->db->get_where('bahan',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all bahan
     */
    function get_all_bahan()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('bahan')->result_array();
    }
        
    /*
     * function to add new bahan
     */
    function add_bahan($params)
    {
        $this->db->insert('bahan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bahan
     */
    function update_bahan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('bahan',$params);
    }
    
    /*
     * function to delete bahan
     */
    function delete_bahan($id)
    {
        return $this->db->delete('bahan',array('id'=>$id));
    }
}
