<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bom by id
     */
    function get_bom($id)
    {
        return $this->db->get_where('bom',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all bom
     */
    function get_all_bom()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('bom')->result_array();
    }
        
    /*
     * function to add new bom
     */
    function add_bom($params)
    {
        $this->db->insert('bom',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bom
     */
    function update_bom($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('bom',$params);
    }
    
    /*
     * function to delete bom
     */
    function delete_bom($id)
    {
        return $this->db->delete('bom',array('id'=>$id));
    }
}
