<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Customer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_login($email,$pass){
        $where=array('email'=>$email,'password'=>$pass);
        return $this->db->get_where('customer',$where);
    }
    
    /*
     * Get tb_costumer by id
     */
    function get_customer($id)
    {
        return $this->db->get_where('customer',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_costumer
     */
    function get_all_customer()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('customer')->result_array();
    }
        
    /*
     * function to add new tb_costumer
     */
    function add_customer($params)
    {
        $this->db->insert('customer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_costumer
     */
    function update_customer($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('customer',$params);
    }
    
    /*
     * function to delete tb_costumer
     */
    function delete_customer($id)
    {
        return $this->db->delete('customer',array('id'=>$id));
    }
}
