<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Karyawan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get karyawan by id
     */
    function get_karyawan($id)
    {
        return $this->db->get_where('karyawan',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all karyawan
     */
    function get_all_karyawan()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('karyawan')->result_array();
    }
        
    /*
     * function to add new karyawan
     */
    function add_karyawan($params)
    {
        $this->db->insert('karyawan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update karyawan
     */
    function update_karyawan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('karyawan',$params);
    }
    
    /*
     * function to delete karyawan
     */
    function delete_karyawan($id)
    {
        return $this->db->delete('karyawan',array('id'=>$id));
    }

    function get_login($user,$pass){
        $where=array('email'=>$user,'password'=>$pass);
        return $this->db->get_where('karyawan',$where);
    }
}
