<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Keranjang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get keranjang by id
     */
    function get_keranjang($id)
    {
        return $this->db->get_where('keranjang',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all keranjang
     */
    function get_all_keranjang()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('keranjang')->result_array();
    }
        
    /*
     * function to add new keranjang
     */
    function add_keranjang($params)
    {
        $this->db->insert('keranjang',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update keranjang
     */
    function update_keranjang($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('keranjang',$params);
    }

    function checkout($id,$params)
    {
        $this->db->where('id_customer',$id)->where('status',1);
        return $this->db->update('keranjang',$params);
    }

    function checkout2($id,$params)
    {
        $this->db->where('id_customer',$id)->where('status',2);
        return $this->db->update('keranjang',$params);
    }
    
    /*
     * function to delete keranjang
     */
    function delete_keranjang($id)
    {
        return $this->db->delete('keranjang',array('id'=>$id));
    }
}
