<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sablon_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sablon_detail by id
     */
    function get_sablon_detail($id)
    {
        return $this->db->get_where('sablon_detail',array('id_keranjang'=>$id))->row_array();
    }
        
    /*
     * Get all sablon_detail
     */
    function get_all_sablon_detail()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('sablon_detail')->result_array();
    }
        
    /*
     * function to add new sablon_detail
     */
    function add_sablon_detail($params)
    {
        $this->db->insert('sablon_detail',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sablon_detail
     */
    function update_sablon_detail($id,$params)
    {
        $this->db->where('id_keranjang',$id);
        return $this->db->update('sablon_detail',$params);
    }
    
    /*
     * function to delete sablon_detail
     */
    function delete_sablon_detail($id)
    {
        return $this->db->delete('sablon_detail',array('id'=>$id));
    }
}
