<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vendor by id
     */
    function get_vendor($id)
    {
        return $this->db->get_where('vendor',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all vendor
     */
    function get_all_vendor()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vendor')->result_array();
    }
        
    /*
     * function to add new vendor
     */
    function add_vendor($params)
    {
        $this->db->insert('vendor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vendor
     */
    function update_vendor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vendor',$params);
    }
    
    /*
     * function to delete vendor
     */
    function delete_vendor($id)
    {
        return $this->db->delete('vendor',array('id'=>$id));
    }

    function get_login($user,$pass){
        $where=array('email'=>$user,'password'=>$pass);
        return $this->db->get_where('vendor',$where);
    }
}
